articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
# www.domain.com/articles/___
urlpatterns = [  # articles:name
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
]

myform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

articles/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-pk',)
    
    def __str__(self):
        return f'{self.pk} - {self.title}'

articles/forms.py
from django import forms


# 사용자에게 입력받는 Field 만 작성
class ArticleForm(forms.Form):
    title = forms.CharField(
        max_length=20,
        label='제목',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Enter the title',
            }
        ),
    )



    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Enter the content',
                'rows': 5,
                'cols': 50,
            }
        )
    )

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from .forms import ArticleForm

# 모든 article 을 보여주는 페이지
def index(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)

# Get 으로 들어오면 생성하는 페이지 rendering
# Post 로 들어오면 생성
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            content = form.cleaned_data.get('content')
            article = Article(title=title, content=content)
            article.save()
            return redirect('articles:index')
        # client 가 입력을 잘못입력했을 때 입력값을 그대로 다시 보여줌
    else:
        form = ArticleForm()
    context = {'form': form}
    return render(request, 'articles/create.html', context)

def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    context = {'article': article}
    return render(request, 'articles/detail.html', context)

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block title %}Create Article{% endblock title %}

{% block body %}
  <h1>Create New Article</h1>

  <form action="{% url 'articles:create' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Create</button>
  <a href="{% url 'articles:index' %}"><button type="button">Cancle</button></a>
  </form>

{% endblock body %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{ article.title }}{% endblock title %}

{% block body %}
<h1>{{ article.title }}</h1>
<p>{{ article.created_at }}</p>
<hr>
<p>{{ article.content }}</p>
<a href="{% url 'articles:index' %}">[Back]</a>
{% endblock body %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block title %}Articles{% endblock title %}

{% block body %}
<h1>Articles</h1>
<a href="{% url 'articles:create' %}">[New]</a>
<hr>
{% for article in articles %}
<div>
  <h3>{{ article.pk }}. {{ article.title }}</h3>
  <p>{{ article.created_at }}</p>
  <a href="{% url 'articles:detail' article.pk %}">[Detail]</a>
</div>
<br>
{% empty %}
<p>아직 게시글이 없습니다.</p>
{% endfor %}
{% endblock body %}

myform/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock title %}</title>
</head>
<body>
  {% block body %}{% endblock body %}
</body>
</html>